[package]
name = "rukari"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rukari"
crate-type = ["cdylib"]  # , "lib"

[dependencies]
log = "0.4"
pyo3 = "0.16.5"
pyo3-asyncio = "0.16.0"
pyo3-log = "0.6.0"
twilight-gateway = "0.11.0"
twilight-model = "0.11.0"

[dependencies.tokio]
features = ["macros", "rt", "sync"]  # , "rt-multi-thread"
version = "1.18.2"
