name: Resync piped

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    paths: ["piped", "piped.toml", "pyproject.toml"]

jobs:
  resync-piped:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Resync Piped
        run: nox -s copy-piped bot-package-diff

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: nox -s is-diff-file-empty
